### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by Zolix-ai**
Verify CircleCI Build

### CODE REVIEW

**Comment by Zolix-ai** [comment]
@Dee-Tyan Great effort so far! but why is CircleCI not getting initialized automatically? Also, make sure CircleCI actually builds the projects not just displaying "Hello World"

Don't forget to also make sure CircleCI gets initialized when a PR is sent from a forked repo

Toggle this on;
image

**Comment by Dee-Tyan** [comment]
> @Dee-Tyan Great effort so far! but why is CircleCI not getting initialized automatically? Also, make sure CircleCI actually builds the projects not just displaying "Hello World"
> 
> Don't forget to also make sure CircleCI gets initialized when a PR is sent from a forked repo
> 
> Toggle this on; image

I've turned on the functionality to build forked PRs, but I'm a bit stuck. 

Circe is new to me, so it's confusing to navigate. For instance, I have tried running the pipeline from scratch to run a build command, but now I have three pipelines running the hello world script. 

I need your help to figure this out. How do I change the run scripts? @Zolix-ai

**Comment by Dee-Tyan** [comment]
> @Dee-Tyan Great effort so far! but why is CircleCI not getting initialized automatically? Also, make sure CircleCI actually builds the projects not just displaying "Hello World"
> 
> Don't forget to also make sure CircleCI gets initialized when a PR is sent from a forked repo
> 
> Toggle this on; image



> > @Dee-Tyan Great effort so far! but why is CircleCI not getting initialized automatically? Also, make sure CircleCI actually builds the projects not just displaying "Hello World"
> > Don't forget to also make sure CircleCI gets initialized when a PR is sent from a forked repo
> > Toggle this on; image
> 
> I've turned on the functionality to build forked PRs, but I'm a bit stuck.
> 
> Circe is new to me, so it's confusing to navigate. For instance, I have tried running the pipeline from scratch to run a build command, but now I have three pipelines running the hello world script.
> 
> I need your help to figure this out. How do I change the run scripts? @Zolix-ai

I think I have figured it out because I am running the build script for the project... please can you confirm? @Zolix-ai 

Screenshot 2023-03-10 at 14 36 13

**Comment by nuilewis** [comment]
Hi, @Dee-Tyan Did you turn on "Only build pull request" in the CircleCI settings? I also think you should create a PR from your `circleci-project-setup` branch into your `master` branch.

image

**Comment by Dee-Tyan** [comment]
> Hi, @Dee-Tyan Did you turn on "Only build pull request" in the CircleCI settings? I also think you should create a PR from your `circleci-project-setup` branch into your `master` branch.
> 
> image

Thanks for the pointer!

@Zolix-ai , I have merged the circleci branch into the master branch

**Comment by Zolix-ai** [comment]
@Dee-Tyan Great job!

**Comment by Dee-Tyan** [comment]
> @Dee-Tyan Great job!

Thank youu!

**Pull request closed without merging**
